name: run-validator
on: pull_request

jobs:
 run-validator:
    name: Run Validatior Script
    runs-on: ubuntu-latest
    steps:
      - name: get the owner of the head repository
        run: echo "PR creator = ${{ github.event.pull_request.user.login }}"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Commit Status Success
        if: ${{ true && true && ( github.event.pull_request.user.login == 'eis-refarch15' || github.event.pull_request.user.login == 'omar123mok') }}
        uses: actions/github-script@v5
        steps:
         - name: making
           run: echo "PR creator = ${{ github.event.pull_request.user.login }}"
      
