name: run-validator
on: push

jobs:
 run-validator:
    name: Run Validatior Script
    runs-on: ubuntu-latest
    steps:
      - name: get the owner of the head repository
        run: echo "PR creator = ${{ github.event.pull_request.user.login }}"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
