name: validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run validation script
      run: |
          pip install pytest --quiet 
          pip install pyaml --quiet 
          pytest -k test_validation.py
